mode: ETH-XGaze
device: cpu
model:
  name: resnet18
face_detector:
  mode: dlib
gaze_estimator:
  checkpoint: ~/.ptgaze/models/eth-xgaze_resnet18.pth
  camera_params: ptgaze/data/calib/sample_params.yaml
  normalized_camera_params: ptgaze/data/calib/normalized_camera_params_eth-xgaze.yaml
  normalized_camera_distance: 0.6
demo:
  use_camera: True
  display_on_screen: True
  wait_time: 1
  image_path: ''
  video_path: ''
  output_dir: ''
  output_file_extension: avi
  head_pose_axis_length: 0.05
  gaze_visualization_length: 0.05
  show_bbox: True
  show_head_pose: False
  show_landmarks: False
  show_normalized_image: False
  show_template_model: False
